### ISSUE TITLE
Another way to get pointer lock?

### ISSUE THREAD

**Issue by greggman** [timeinvariant/gorescript#5]
I'm on Mac Laptop, there is no easy "right click".

**Comment by alvinlai** [comment]
Hold control and click?

**Comment by greggman** [comment]
I'm not an idiot thank you :-1: 

 Holding control and click doesn't work

**Comment by alvinlai** [comment]
I'm sorry

**Comment by dirkk0** [comment]
I am on a Mac and it works for me.
http://www.cnet.com/how-to/five-ways-to-right-click-on-a-mac-trackpad/

**Comment by capnmidnight** [comment]
In the apps I've built, I've always combined fullscreen and pointer lock into the same action, triggered by clicking an on-screen button.

**Comment by SyntaxStacks** [comment]
Right click is a double finger click on a mac @greggman
